import "./Loader.scss";

export const Loader = () => {
  return (
    <div className="loader" data-testid="loader">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 100 100"
        preserveAspectRatio="xMidYMid"
        width="50"
        height="50"
        xmlnsXlink="http://www.w3.org/1999/xlink"
      >
        <g>
          <circle
            cx="50"
            cy="50"
            fill="none"
            stroke="#e15b64"
            strokeWidth="10"
            r="35"
            strokeDasharray="164.93361431346415 56.97787143782138"
          >
            <animateTransform
              attributeName="transform"
              type="rotate"
              repeatCount="indefinite"
              dur="1s"
              values="0 50 50;360 50 50"
              keyTimes="0;1"
            ></animateTransform>
          </circle>
          <g></g>
        </g>
        {/* <!-- [ldio] generated by https://loading.io --> */}
      </svg>
    </div>
  );
};
